@echo off
cd /d E:\Workspace
echo [GitNexus] Limpando indice...
call npx gitnexus clean
echo [GitNexus] Re-indexando...
call npx gitnexus analyze --force
echo [GitNexus] Abrindo Web UI...
start "" "https://gitnexus.vercel.app/?project=Workspace&server=http%%3A%%2F%%2Flocalhost%%3A4747"
echo [GitNexus] Iniciando servidor...
npx gitnexus serve
